name: Build MKW-SP

on:
  push:
    paths-ignore:
      - 'www/**'
      - 'tools/**'
      - '.github/workflows/run_tidy.yml'
      - '.github/workflows/clean_bmg.yml'
      - '.github/workflows/build_tools.yml'
  pull_request:
    paths-ignore:
      - 'www/**'
      - 'tools/**'
      - '.github/workflows/run_tidy.yml'
      - '.github/workflows/clean_bmg.yml'
      - '.github/workflows/build_tools.yml'

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        profile:
          - debug
          - test
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest
    env:
      DEVKITPPC: opt/devkitpro/devkitPPC
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install ninja
        run: sudo apt install ninja-build
      - name: Install protoc
        run: sudo apt install protobuf-compiler
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
      - name: Install Packages
        run: pip install -r requirements.txt
      - name: Compile
        run: ./build.py --ci -- ${{ matrix.profile }}
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: mkw-sp-${{ matrix.profile }}
          path: out/${{ matrix.profile }}

  format:
    name: Format
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install clang-format-15
      - name: Format MKW-SP
        run: |
          dirs="common include loader payload stub"
          find $dirs -regex '.*\.\(c\|h\|cc\|hh\)' | xargs clang-format-15 --dry-run -Werror
